---
- name: Configure hosts & deploy application
  hosts: all


  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.15.204


  tasks:
    - name: Change mongo config file
      become: yes
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod      
      tags: db-tag

    - name: Add unit file for Puma
      become: yes
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma
      tags: app-tag

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
      tags: db-tag

    - name: enable puma
      become: yes
      systemd:
        name: puma
        enabled: yes
      tags: app-tag

    - name: Fetch the latest version of application code
      git: 
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: reload puma
      tags: deploy-tag

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag


  handlers:
    - name: restart mongod
      become: yes
      service:
        name: mongod
        state: restarted

    - name: reload puma
      become: yes
      systemd:
        name: puma
        state: restarted
